
server:
  host: "0.0.0.0"
  port: 8000
  bodyLimit: 4096

request:
  header: "X-Gitlab-token"
  token: "llwixfry82347r6bx23874bvr6238x2423kk"
  param: "hook"

hooks:
  'default':
    executor: "/bin/python"
    script: "./examples/python_example.py"
  'example':
    executor: "/bin/sh"
    script: "./examples/bash_example.sh"